#! /bin/bash
# FS QA Test 002
#
# Visible whiteouts in pure-upper directory
#
# https://bugzilla.kernel.org/show_bug.cgi?id=109611
# https://github.com/docker/docker/issues/9572
#
#-----------------------------------------------------------------------
# Copyright (c) 2016 Konstantin Khlebnikov.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
	rm -fr $TEST_DEV/upper/$seq.pure
	rm -fr $TEST_DEV/upper/$seq.file
	rm -fr $TEST_DEV/lower/$seq.file
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs overlay
_supported_os Linux
_require_test

echo "Silence is golden."

touch $TEST_DEV/lower/$seq.file

cd $TEST_DIR
mkdir $seq.pure
mv $seq.file $seq.pure
rm $seq.pure/$seq.file
ls $seq.pure

# success, all done
status=0
exit
